### ISSUE TITLE
已经docker部署，请问下企微WechatApp如何发消息给指定用户？

### ISSUE THREAD

**Issue by Yafeiml** [CaoMeiYouRen/push-all-in-cloud#1]
{
  "title": "你好",
  "desp": "YingHui\n13663013063",
  "config": {
    "WX_APP_USERID": ",YingHui"
  }
} json换了很多写法都不好使。

**Comment by Yafeiml** [comment]
噢，感谢回复，实际上我这样测试过了，所有的用户都可以收到信息。

**Comment by CaoMeiYouRen** [comment]
> 噢，感谢回复，实际上我这样测试过了，所有的用户都可以收到信息。


企业微信应用推送，文档：https://work.weixin.qq.com/api/doc/90000/90135/90664
    /**
     * 指定接收消息的成员。若不指定则默认为 ”@all”。
     * 成员ID列表（多个接收者用‘|’分隔，最多支持1000个）。
     * 特殊情况：指定为”@all”，则向该企业应用的全部成员发送。
     *
     */
    WX_APP_USERID?: string

**Comment by Yafeiml** [comment]
改为forward方法可以了，看来push不能再次接收参数了
